"""Stage 6 pipeline replay: real KITTI OXTS + synthetic targets, failure injection, verdict.

Publishes the Stage 2 stream (/eskf/init, /imu/data, /gps/fix) in kitti_replay's parity-critical
order, plus a 10 Hz /detections frame in base_link. eskf_node estimates the ego pose,
detection_transform_node converts those detections to map_bev with that ESTIMATE, and tracker_node
tracks them -- so localization error lands in the track positions, which is the point of the stage.

Detections are generated by projecting ENU target truth into base_link with the GROUND-TRUTH OXTS
pose, because that is what a real sensor sees. The estimate is used only on the way back out,
inside detection_transform_node. Using truth on BOTH sides would make the coupling a silent no-op
while every gate still passed.

kitti_replay.py is frozen: its geometry helpers are imported, never copied or edited, so the
Stage 2 parity gate is untouched.

Records data/cache/stage6_<mode>.npz (schema: plan Task 4 step 1), evaluates that mode's gate from
kf_bringup.stage6_gates, prints every report line prefixed STAGE6, and exits 0 on PASS / 1 on FAIL.

Every alignment between /ego/state, detection frames and /tracks is by EXACT int64-nanosecond
stamp; the float-second columns exist for plotting and for the dropout windows only. Float seconds
do not compare equal, and a nearest-match fallback would turn a recording bug into a plausible
error curve.
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

import numpy as np
import rclpy
import rclpy.logging
from geometry_msgs.msg import PointStamped
from kf_msgs.msg import Detection, DetectionArray, EgoState, TrackArray
from nav_msgs.msg import Odometry
from rclpy.node import Node
from rclpy.qos import QoSDurabilityPolicy, QoSHistoryPolicy, QoSProfile, QoSReliabilityPolicy
from sensor_msgs.msg import Imu

from kf_bringup.kitti_replay import _euler_to_quat, _quat_to_rotmat, _stamp_from_secs
from kf_bringup.stage6_gates import MODES, evaluate
from kf_bringup.targets import (
    BOX_DIM, H, L, N_TARGETS, W, X, Y, YAW, Z, TargetConfig, detect, enu_to_base_link,
    enu_to_map_bev, map_bev_to_enu, target_truth,
)

STATE_DIM = 4          # Track.state is [x, z, vx, vz] in map_bev -- no height, see _track_enu
BASE_FRAME = "base_link"
MAP_FRAME = "map"
MAP_BEV_FRAME = "map_bev"
DRAIN_QUIET_S = 0.5    # how long the message counts must stand still before the drain ends

# Declared parameters, in one place so _params_dict cannot drift out of sync with the
# declarations. full_pipeline.yaml and the launch presets override them by name.
PARAMS: dict = {
    "cache_path": "/workspace/data/cache/kitti_raw_2011_09_26_drive_0001_extract_oxts_v1.npz",
    "output_npz": "/workspace/data/cache/stage6_baseline.npz",
    "baseline_npz": "",          # "" = none; a ratio gate then fails loudly instead of passing
    "mode": "baseline",
    "gps_std_m": 0.75,
    "gps_rate_divisor": 10,      # 100 Hz / 10 = 10 Hz GPS
    "det_rate_divisor": 10,      # 10 Hz detections
    "seed": 0,
    "rate_scale": 0.0,           # 0 = as fast as possible; 1.0 = wall clock
    "publish_period_s": 0.001,
    "gps_dropout_s": [0.0, 0.0],       # suppression window, seconds from t[0]
    "det_dropout_s": [0.0, 0.0],       # suppression window, seconds from t[0]
    "imu_accel_bias_xyz": [0.0, 0.0, 0.0],
    "p_detect": 0.9,
    "det_pos_std": 0.35,
    "det_yaw_std": 0.03,
    "clutter_lambda": 0.0,
    "max_range_m": 60.0,
    "fov_deg": 90.0,
    "maneuver_target": -1,
    "maneuver_start_s": 5.0,
    "maneuver_omega": 0.4,
    "drain_timeout_s": 10.0,
    # Not in the plan's table, both copied from tracking_replay: RELIABLE+VOLATILE does not
    # redeliver to a late-joining peer, so publishing before the three C++ nodes have matched
    # silently loses the head of the run.
    "discovery_timeout_s": 30.0,
    "settle_s": 0.5,
}


def _ns(stamp) -> int:
    """int64 nanoseconds from a builtin_interfaces/Time, the way rclcpp::Time reads it."""
    return int(stamp.sec) * 1_000_000_000 + int(stamp.nanosec)


def _stamp_ns(t: float):
    """(stamp message, its nanosecond key), both from the SAME _stamp_from_secs result, so the
    recorded key is byte-identical to the header every downstream node echoes back."""
    stamp = _stamp_from_secs(t)
    return stamp, _ns(stamp)


def _visible_mask(boxes_b: np.ndarray, cfg: TargetConfig) -> np.ndarray:
    """The FOV/range gate targets.detect applies, evaluated without consuming the RNG.

    Deliberately duplicated from targets.detect rather than refactored out of it: detect() returns
    only survivors and is frozen for this task, while `target_visible` has to be recorded for every
    target on every frame, including frames whose detections are suppressed. The three conditions
    below must stay identical to detect()'s.
    """
    half_fov = math.radians(cfg.fov_deg) * 0.5
    out = np.zeros(boxes_b.shape[0], dtype=bool)
    for i in range(boxes_b.shape[0]):
        bx, by = float(boxes_b[i, X]), float(boxes_b[i, Y])
        if bx <= 0.0:
            continue
        if math.hypot(bx, by) >= cfg.max_range_m:
            continue
        if abs(math.atan2(by, bx)) >= half_fov:
            continue
        out[i] = True
    return out


class PipelineReplay(Node):
    def __init__(self) -> None:
        super().__init__("pipeline_replay")

        for name, default in PARAMS.items():
            self.declare_parameter(name, default)

        p = self.get_parameter
        self._mode       = str(p("mode").value)
        self._out_path   = Path(str(p("output_npz").value))
        self._baseline   = str(p("baseline_npz").value)
        gps_std          = float(p("gps_std_m").value)
        gps_divisor      = int(p("gps_rate_divisor").value)
        det_divisor      = int(p("det_rate_divisor").value)
        seed             = int(p("seed").value)
        self._rate_scale = float(p("rate_scale").value)
        self._period     = float(p("publish_period_s").value)
        self._drain_s    = float(p("drain_timeout_s").value)
        self._discovery  = float(p("discovery_timeout_s").value)
        self._settle     = float(p("settle_s").value)
        self._imu_bias   = np.asarray(p("imu_accel_bias_xyz").value, dtype=float).reshape(-1)

        # A typo in `mode` must be FATAL at startup, never a silently skipped gate -- the same
        # discipline tracker_node applies to its `cost` parameter.
        if self._mode not in MODES:
            raise ValueError(f"parameter `mode` must be one of {list(MODES)}, got {self._mode!r}")
        if gps_divisor < 1 or det_divisor < 1:
            raise ValueError(f"gps_rate_divisor and det_rate_divisor must be >= 1, got "
                             f"{gps_divisor} and {det_divisor}")
        if self._imu_bias.size != 3:
            raise ValueError(f"imu_accel_bias_xyz needs 3 entries, got {self._imu_bias.size}")

        # TargetConfig validates its own ranges (p_detect, the stds, fov, maneuver_target).
        self._cfg = TargetConfig(
            p_detect=float(p("p_detect").value),
            det_pos_std=float(p("det_pos_std").value),
            det_yaw_std=float(p("det_yaw_std").value),
            clutter_lambda=float(p("clutter_lambda").value),
            max_range_m=float(p("max_range_m").value),
            fov_deg=float(p("fov_deg").value),
            maneuver_target=int(p("maneuver_target").value),
            maneuver_start_s=float(p("maneuver_start_s").value),
            maneuver_omega=float(p("maneuver_omega").value),
        )

        cache = np.load(str(p("cache_path").value))
        self._ts    = np.asarray(cache["timestamps"], dtype=float)      # (N,)
        self._enu   = np.asarray(cache["enu_position_m"], dtype=float)  # (N, 3) ENU
        self._vel_b = np.asarray(cache["velocity"], dtype=float)        # (N, 3) body
        self._rpy   = np.asarray(cache["roll_pitch_yaw"], dtype=float)  # (N, 3)
        self._acc_b = np.asarray(cache["accel_body"], dtype=float)      # (N, 3)
        self._gyr_b = np.asarray(cache["gyro_body"], dtype=float)       # (N, 3)
        n = int(self._ts.size)
        if n < 3:
            raise ValueError(f"{p('cache_path').value}: {n} OXTS samples is too few to replay")
        self._n = n

        # Stamp keys come from the SAME helper that stamps the published messages, so the recorded
        # t_ns column and every echoed header agree exactly.
        self._t_ns = np.array([_stamp_ns(float(t))[1] for t in self._ts], dtype=np.int64)

        # Dropout windows. The parameters are "seconds from t[0]", so the suppression test and the
        # recorded column are BOTH t[0] + parameter -- one base, converted on both sides or
        # neither. On drive_0001 t[0] == 0.0, so the two are numerically identical there.
        t0 = float(self._ts[0])
        self._gps_win = self._window(t0, p("gps_dropout_s").value)
        self._det_win = self._window(t0, p("det_dropout_s").value)

        # GPS measurements, in kitti_replay.build_gps_measurements' exact call order (indices,
        # then one rng.normal of shape (len(indices), 3)), so the same seed reproduces the Stage 2
        # noise stream unchanged.
        idx = np.arange(0, n, gps_divisor)
        gps_z = self._enu[idx] + np.random.default_rng(seed).normal(0.0, gps_std, (len(idx), 3))
        self._gps = {int(i): gps_z[j] for j, i in enumerate(idx)}

        # ONE detector RNG for the whole run, so the detection stream is a single reproducible
        # sequence. It is drawn on every frame, including suppressed ones (see _frame_step).
        self._rng = np.random.default_rng(seed)

        # Initial nominal state, mirroring initial_state_from_oxts(sequence, 0).
        self._q0   = _euler_to_quat(*(float(v) for v in self._rpy[0]))
        self._pos0 = self._enu[0]
        self._vel0 = _quat_to_rotmat(self._q0) @ self._vel_b[0]

        # Detection frames: OXTS steps 1..N-1 on the divisor. Step 0 is excluded because the ESKF
        # publishes no state for it, so a frame there could never be transformed.
        self._frame_k = [k for k in range(1, n) if k % det_divisor == 0]
        self._nf = len(self._frame_k)
        if self._nf == 0:
            raise ValueError(f"det_rate_divisor={det_divisor} yields no detection frame over "
                             f"{n} OXTS samples")
        self._frame_of_k = {k: f for f, k in enumerate(self._frame_k)}
        self._frame_t = self._ts[self._frame_k]
        self._frame_ns = self._t_ns[self._frame_k]
        self._frame_of_ns = {int(v): f for f, v in enumerate(self._frame_ns)}

        # Target truth on the DETECTION-frame time base. target_truth puts the maneuver onset at
        # frame_t[0] + maneuver_start_s, which is exactly what stage6_gates._gate_maneuver
        # recomputes from the recorded frame_t; handing it the full OXTS base instead would shift
        # the two apart by one detection period. Targets are anchored to the ego pose at OXTS index
        # 0 (spec 5.1), one detection period before the first frame.
        self._truth = target_truth(
            self._cfg, self._frame_t, self._enu[0], float(self._rpy[0, 2]),
            float(math.hypot(self._vel_b[0, 0], self._vel_b[0, 1])))

        self._visible = np.zeros((self._nf, N_TARGETS), dtype=bool)
        self._dets: dict[int, tuple[np.ndarray, np.ndarray]] = {}   # frame -> (boxes, src ids)

        # /ego/state is kept in arrival order (the imu_bias gate reads the LAST bias sample);
        # /tracks is keyed by the detection stamp tracker_node echoes back.
        self._ego: list[tuple[int, np.ndarray, np.ndarray, np.ndarray]] = []
        self._tracks: dict[int, list[tuple[int, np.ndarray, float, np.ndarray]]] = {}
        self._track_msgs = 0
        self._track_unmatched = 0
        self._track_duplicate = 0

        reliable_qos = QoSProfile(
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=2000,
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=QoSDurabilityPolicy.VOLATILE,
        )
        init_qos = QoSProfile(
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=1,
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=QoSDurabilityPolicy.TRANSIENT_LOCAL,
        )

        self._init_pub  = self.create_publisher(Odometry,       "/eskf/init",     init_qos)
        self._imu_pub   = self.create_publisher(Imu,            "/imu/data",      reliable_qos)
        self._gps_pub   = self.create_publisher(PointStamped,   "/gps/fix",       reliable_qos)
        self._det_pub   = self.create_publisher(DetectionArray, "/detections",    reliable_qos)
        self._truth_pub = self.create_publisher(DetectionArray, "/targets/truth", reliable_qos)

        self.create_subscription(EgoState,   "/ego/state", self._on_ego,    reliable_qos)
        self.create_subscription(TrackArray, "/tracks",    self._on_tracks, reliable_qos)

        self.get_logger().info(
            f"pipeline_replay ready: mode={self._mode} oxts={n} frames={self._nf} "
            f"gps_window={self._gps_win.tolist()} det_window={self._det_win.tolist()} "
            f"imu_accel_bias={self._imu_bias.tolist()} seed={seed} out={self._out_path}")

    # ------------------------------------------------------------------
    # Setup helpers.
    # ------------------------------------------------------------------
    @staticmethod
    def _window(t0: float, value) -> np.ndarray:
        """[start, end] absolute seconds, or the [0, 0] "not injected" sentinel the gates read."""
        w = np.asarray(value, dtype=float).reshape(-1)
        if w.size < 2 or not w[1] > w[0]:
            return np.zeros(2)
        return np.array([t0 + float(w[0]), t0 + float(w[1])])

    @staticmethod
    def _suppressed(t: float, window: np.ndarray) -> bool:
        """Inclusive on both ends, the same test the gates apply to the recorded window."""
        return bool(window[1] > window[0] and window[0] <= t <= window[1])

    def _params_dict(self) -> dict:
        """Every resolved parameter, FLAT. stage6_gates._params reads `maneuver_target` and
        `maneuver_start_s` straight off the top level of this dict, so it must not be nested."""
        out: dict = {}
        for name in PARAMS:
            value = self.get_parameter(name).value
            if value is None or isinstance(value, (str, bool, int, float)):
                out[name] = value
            else:   # double/int arrays arrive as array.array or list depending on the rmw
                out[name] = [v.item() if hasattr(v, "item") else v for v in value]
        out["output_npz"] = str(self._out_path)
        return out

    # ------------------------------------------------------------------
    # Subscriptions.
    # ------------------------------------------------------------------
    def _on_ego(self, msg: EgoState) -> None:
        self._ego.append((
            _ns(msg.header.stamp),
            np.array([msg.pose.position.x, msg.pose.position.y, msg.pose.position.z]),
            np.array([msg.accel_bias.x, msg.accel_bias.y, msg.accel_bias.z]),
            np.array([msg.gyro_bias.x, msg.gyro_bias.y, msg.gyro_bias.z]),
        ))

    def _on_tracks(self, msg: TrackArray) -> None:
        """Snapshot id, state, height and mode probabilities NOW: the C++ BoxTrack/ImmFilter mutate
        in place and modeProbabilities() hands back a reference into live filter state."""
        self._track_msgs += 1
        key = _ns(msg.header.stamp)
        if key not in self._frame_of_ns:
            self._track_unmatched += 1
            return
        if key in self._tracks:
            self._track_duplicate += 1
            return
        self._tracks[key] = [
            (int(t.id), np.asarray(t.state, dtype=float), float(t.pose.position.y),
             np.asarray(t.mode_probabilities, dtype=float))
            for t in msg.tracks
        ]

    # ------------------------------------------------------------------
    # Publishing.
    # ------------------------------------------------------------------
    def _spin(self) -> None:
        rclpy.spin_once(self, timeout_sec=self._period)

    def _publish_init(self) -> None:
        msg = Odometry()
        msg.header.stamp, _key = _stamp_ns(float(self._ts[0]))
        msg.header.frame_id = MAP_FRAME
        msg.pose.pose.position.x = float(self._pos0[0])
        msg.pose.pose.position.y = float(self._pos0[1])
        msg.pose.pose.position.z = float(self._pos0[2])
        msg.pose.pose.orientation.w = float(self._q0[0])   # scalar-first -> ROS w-first
        msg.pose.pose.orientation.x = float(self._q0[1])
        msg.pose.pose.orientation.y = float(self._q0[2])
        msg.pose.pose.orientation.z = float(self._q0[3])
        msg.twist.twist.linear.x = float(self._vel0[0])
        msg.twist.twist.linear.y = float(self._vel0[1])
        msg.twist.twist.linear.z = float(self._vel0[2])
        self._init_pub.publish(msg)

    def _publish_imu(self, src: int, stamp) -> None:
        msg = Imu()
        msg.header.stamp = stamp                 # t[k]: the node's dt is t[k] - t[k-1]
        msg.header.frame_id = BASE_FRAME
        # The injected bias is added to the MEASUREMENT, in the body frame, exactly the way a real
        # accelerometer offset appears to the filter.
        msg.linear_acceleration.x = float(self._acc_b[src, 0] + self._imu_bias[0])
        msg.linear_acceleration.y = float(self._acc_b[src, 1] + self._imu_bias[1])
        msg.linear_acceleration.z = float(self._acc_b[src, 2] + self._imu_bias[2])
        msg.angular_velocity.x = float(self._gyr_b[src, 0])
        msg.angular_velocity.y = float(self._gyr_b[src, 1])
        msg.angular_velocity.z = float(self._gyr_b[src, 2])
        self._imu_pub.publish(msg)
        self._spin()

    def _publish_gps(self, k: int, stamp) -> None:
        z = self._gps[k]
        msg = PointStamped()
        msg.header.stamp = stamp
        msg.header.frame_id = MAP_FRAME
        msg.point.x = float(z[0])
        msg.point.y = float(z[1])
        msg.point.z = float(z[2])
        self._gps_pub.publish(msg)
        self._spin()

    @staticmethod
    def _box_array(boxes, stamp, frame_id: str, yaw_about_y: bool) -> DetectionArray:
        """One DetectionArray from (m, BOX_DIM) rows.

        `yaw_about_y` selects the axis the yaw is encoded about. base_link has z up, so
        detection_transform_node decodes atan2(2(wz+xy), 1-2(y^2+z^2)); map_bev has y down, which
        is the encoding box3d/tracker_node already use. Getting this backwards silently rotates
        every box instead of failing, so it is an explicit argument, not a copy-paste.
        """
        msg = DetectionArray()
        msg.header.stamp = stamp
        msg.header.frame_id = frame_id
        for row in np.asarray(boxes, dtype=float).reshape(-1, BOX_DIM):
            d = Detection()
            d.pose.position.x = float(row[X])
            d.pose.position.y = float(row[Y])
            d.pose.position.z = float(row[Z])
            half = float(row[YAW]) * 0.5
            d.pose.orientation.w = math.cos(half)
            d.pose.orientation.x = 0.0
            d.pose.orientation.y = math.sin(half) if yaw_about_y else 0.0
            d.pose.orientation.z = 0.0 if yaw_about_y else math.sin(half)
            d.dimensions.x = float(row[L])
            d.dimensions.y = float(row[W])
            d.dimensions.z = float(row[H])
            d.object_id = -1     # a detector emits no identity; src ids are recorded, never sent
            msg.detections.append(d)
        return msg

    def _frame_step(self, f: int, k: int, stamp) -> None:
        """Generate frame `f` (OXTS index `k`), record its truth, and publish it.

        A suppressed frame is published EMPTY, not skipped. Detection dropout means the detector
        found nothing; a detector node that stops publishing is a different failure mode, and it
        is not the one PRD 6.2.4 asks for. tracker_node is purely callback-driven with a FIXED dt
        parameter -- "An EMPTY frame must still step the tracker so every track coasts and ages --
        do not early-return on msg->detections.empty()" (tracker_node.cpp) -- so an ABSENT frame
        steps the tracker zero times: nothing coasts, nothing ages, max_age never fires, and the
        track resumes from where it froze rather than from where it predicted.
        """
        rot = _quat_to_rotmat(_euler_to_quat(*(float(v) for v in self._rpy[k])))
        boxes_b = enu_to_base_link(self._truth[f], self._enu[k], rot)   # GROUND-TRUTH projection
        self._visible[f] = _visible_mask(boxes_b, self._cfg)

        # Drawn even when the frame is suppressed, so a det_dropout run's detector stream stays
        # aligned with the baseline's: the only difference the injection makes is the emptied
        # frame, not a different noise sequence from the gap onward. The draw is DISCARDED below,
        # never published -- moving it after the suppression test would desynchronise the stream.
        dets, src = detect(boxes_b, self._rng, self._cfg)
        if self._suppressed(float(self._ts[k]), self._det_win):
            dets = np.zeros((0, BOX_DIM))
            src = np.zeros(0, dtype=int)

        self._dets[f] = (dets, src)
        self._det_pub.publish(self._box_array(dets, stamp, BASE_FRAME, yaw_about_y=False))
        self._spin()
        self._truth_pub.publish(
            self._box_array(enu_to_map_bev(self._truth[f]), stamp, MAP_BEV_FRAME,
                            yaw_about_y=True))
        self._spin()

    # ------------------------------------------------------------------
    # Replay.
    # ------------------------------------------------------------------
    def _await_peers(self) -> bool:
        deadline = time.monotonic() + self._discovery
        while time.monotonic() < deadline:
            rclpy.spin_once(self, timeout_sec=0.05)
            if (self._imu_pub.get_subscription_count() > 0
                    and self._det_pub.get_subscription_count() > 0
                    and self.count_publishers("/ego/state") > 0
                    and self.count_publishers("/tracks") > 0):
                self.get_logger().info("eskf_node, detection_transform_node and tracker_node "
                                       "discovered on all four topics")
                return True
        self.get_logger().error(
            f"FAIL(no-peer): after {self._discovery:.1f} s, /imu/data had "
            f"{self._imu_pub.get_subscription_count()} subscriber(s), /detections "
            f"{self._det_pub.get_subscription_count()}, /ego/state "
            f"{self.count_publishers('/ego/state')} publisher(s), /tracks "
            f"{self.count_publishers('/tracks')}. Check eskf_node, detection_transform_node and "
            f"tracker_node for a startup crash.")
        return False

    def _drain(self) -> None:
        """Spin until /ego/state and /tracks stop arriving, or the timeout expires. The transform
        node lags one IMU period by construction, so the tail always needs draining."""
        deadline = time.monotonic() + self._drain_s
        last_change = time.monotonic()
        prev = (-1, -1)
        while time.monotonic() < deadline:
            rclpy.spin_once(self, timeout_sec=0.05)
            cur = (len(self._ego), self._track_msgs)
            if cur != prev:
                prev, last_change = cur, time.monotonic()
            elif time.monotonic() - last_change >= DRAIN_QUIET_S:
                return
        self.get_logger().warn(f"drain hit its {self._drain_s:.1f} s timeout with messages still "
                               f"arriving; the tail of the run may be missing")

    def run(self) -> int:
        if not self._await_peers():
            # A gate that cannot be evaluated FAILS with the reason stated -- it never goes
            # unreported, because a missing verdict and a passing one look alike in a run log.
            print(f"STAGE6 [FAIL] {self._mode}: the pipeline never came up, so no gate was "
                  f"evaluated (see the FAIL(no-peer) line above)", flush=True)
            print(f"STAGE6 {self._mode}: FAIL", flush=True)
            return 1

        self._publish_init()
        settle_until = time.monotonic() + self._settle
        while time.monotonic() < settle_until:      # transient_local delivery + DDS matching
            rclpy.spin_once(self, timeout_sec=0.05)

        ts = self._ts
        # kitti_replay's ordering, extended. For step k: IMU[k-1] stamped t[k] FIRST so predict
        # runs before any update, then GPS[k], then the detection frame. eskf_node emits
        # /ego/state for t[k] only once the IMU for t[k+1] arrives, so the detection frame at t[k]
        # waits exactly one step inside detection_transform_node -- by design, not by accident.
        for k in range(1, self._n):
            stamp, _key = _stamp_ns(float(ts[k]))
            self._publish_imu(k - 1, stamp)

            if k in self._gps and not self._suppressed(float(ts[k]), self._gps_win):
                self._publish_gps(k, stamp)

            f = self._frame_of_k.get(k)
            if f is not None:
                self._frame_step(f, k, stamp)

            if self._rate_scale > 0.0:
                time.sleep(max(0.0, float(ts[k] - ts[k - 1]) / self._rate_scale))

        # Duplicate-stamp flush (dt == 0): the node publishes its pending step without predicting
        # again, so all N-1 steps reach us.
        self._publish_imu(self._n - 2, _stamp_ns(float(ts[self._n - 1]))[0])
        self.get_logger().info(
            f"replay done: {self._n - 1} IMU steps + flush, {len(self._dets)}/{self._nf} "
            f"detection frames published")

        self._drain()
        self.get_logger().info(
            f"collected {len(self._ego)} /ego/state and {self._track_msgs} /tracks "
            f"({len(self._tracks)} matched to a frame, {self._track_unmatched} with an unknown "
            f"stamp, {self._track_duplicate} duplicate stamps)")

        return self._verdict(self._write_npz())

    # ------------------------------------------------------------------
    # Recording.
    # ------------------------------------------------------------------
    @staticmethod
    def _track_enu(state: np.ndarray, pose_y: float) -> np.ndarray:
        """map_bev track -> ENU position. state is [x, z, vx, vz] and carries NO height, so the
        height comes from the POSE: ENU = (x_bev, z_bev, -y_bev)."""
        box = np.zeros(BOX_DIM)
        box[X], box[Y], box[Z] = float(state[0]), float(pose_y), float(state[1])
        return map_bev_to_enu(box)[[X, Y, Z]]

    def _write_npz(self) -> dict:
        nf = self._nf
        det_n = np.zeros(nf, dtype=np.int32)
        trk_n = np.zeros(nf, dtype=np.int32)
        for f, (boxes, _src) in self._dets.items():
            det_n[f] = int(boxes.shape[0])
        rows_by_frame: dict[int, list] = {}
        for key, rows in self._tracks.items():
            f = self._frame_of_ns[key]
            rows_by_frame[f] = rows
            trk_n[f] = len(rows)

        # Ragged axes are padded to the observed maximum with an explicit count column -- the same
        # shape contract write_py_tracker_refs.py uses, and track_count is what every gate reads.
        # The floor of 1 keeps the arrays 3-D even on a run that produced nothing, so a consumer
        # reports "no tracks" instead of crashing on an empty axis.
        d_max = max(1, int(det_n.max()))
        k_max = max(1, int(trk_n.max()))
        b_max = max(1, max((r[3].size for rows in rows_by_frame.values() for r in rows),
                           default=0))

        det_boxes = np.full((nf, d_max, BOX_DIM), np.nan)
        det_src   = np.full((nf, d_max), -1, dtype=np.int32)
        for f, (boxes, src) in self._dets.items():
            m = int(boxes.shape[0])
            det_boxes[f, :m] = boxes
            det_src[f, :m] = src

        trk_ids   = np.full((nf, k_max), -1, dtype=np.int32)
        trk_state = np.full((nf, k_max, STATE_DIM), np.nan)
        trk_enu   = np.full((nf, k_max, 3), np.nan)
        trk_mode  = np.full((nf, k_max, b_max), np.nan)
        for f, rows in rows_by_frame.items():
            for j, (tid, state, pose_y, mu) in enumerate(rows):
                trk_ids[f, j] = tid
                if state.size == STATE_DIM:
                    trk_state[f, j] = state
                    trk_enu[f, j] = self._track_enu(state, pose_y)
                else:
                    self.get_logger().warn(f"frame {f} track {tid} published a state of length "
                                           f"{state.size} (expected {STATE_DIM}); recorded as NaN")
                trk_mode[f, j, :mu.size] = mu

        ego_ns  = np.array([e[0] for e in self._ego], dtype=np.int64)
        ego_pos = np.stack([e[1] for e in self._ego]) if self._ego else np.zeros((0, 3))
        ego_ba  = np.stack([e[2] for e in self._ego]) if self._ego else np.zeros((0, 3))
        ego_bg  = np.stack([e[3] for e in self._ego]) if self._ego else np.zeros((0, 3))

        run = {
            "mode":             np.array(self._mode),
            "params_json":      np.array(json.dumps(self._params_dict(), sort_keys=True)),
            "t":                self._ts,
            "t_ns":             self._t_ns,
            "ego_truth":        self._enu,
            "ego_est":          ego_pos,
            "ego_est_t_ns":     ego_ns,
            "ego_accel_bias":   ego_ba,
            "ego_gyro_bias":    ego_bg,
            "frame_t":          self._frame_t,
            "frame_t_ns":       self._frame_ns,
            "target_truth_enu": self._truth,
            "target_visible":   self._visible,
            "det_count":        det_n,
            "det_boxes":        det_boxes,
            "det_src_id":       det_src,
            "track_count":      trk_n,
            "track_ids":        trk_ids,
            "track_state":      trk_state,
            "track_pos_enu":    trk_enu,
            "track_mode":       trk_mode,
            "gps_window":       self._gps_win,
            "det_window":       self._det_win,
            "imu_bias_xyz":     self._imu_bias,
        }
        self._out_path.parent.mkdir(parents=True, exist_ok=True)
        np.savez(str(self._out_path), **run)
        self.get_logger().info(f"wrote {self._out_path} (F={nf}, D={d_max}, K={k_max}, B={b_max})")
        return run

    # ------------------------------------------------------------------
    # Verdict.
    # ------------------------------------------------------------------
    def _load_baseline(self) -> dict | None:
        if not self._baseline:
            return None
        path = Path(self._baseline)
        if not path.is_file():
            self.get_logger().error(f"baseline_npz {path} does not exist; a ratio gate will report "
                                    f"the missing baseline rather than pass without one")
            return None
        with np.load(path, allow_pickle=False) as npz:
            return {key: npz[key] for key in npz.files}

    def _verdict(self, run: dict) -> int:
        passed, lines = evaluate(self._mode, run, self._load_baseline())
        for line in lines:
            print(f"STAGE6 {line}", flush=True)
        print(f"STAGE6 {self._mode}: {'PASS' if passed else 'FAIL'}", flush=True)
        return 0 if passed else 1


def main() -> None:
    rclpy.init()
    node = None
    code = 1
    try:
        node = PipelineReplay()
        code = node.run()
    except KeyboardInterrupt:
        print("STAGE6 interrupted before the gate ran", file=sys.stderr, flush=True)
        code = 130
    except Exception as exc:                   # noqa: BLE001 -- any startup failure is fatal here
        # "fatal error:" deliberately does not match run_stage6.py's verdict regex: a crash has to
        # be summarised as MISSING, never mistaken for a PASS/FAIL line.
        rclpy.logging.get_logger("pipeline_replay").fatal(f"aborting: {exc}")
        print(f"STAGE6 fatal error: {type(exc).__name__}: {exc}", file=sys.stderr, flush=True)
        code = 1
    finally:
        if node is not None:
            node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
    sys.exit(code)


if __name__ == "__main__":
    main()
